config/routes.rb
Rails.application.routes.draw do

	root 'tubes#index'
  resources :tubes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tube.rb
class Tube < ApplicationRecord
    mount_uploader :video, VideoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tubes_controller.rb
class TubesController < ApplicationController
  before_action :set_tube, only: [:show, :edit, :update, :destroy]

  # GET /tubes
  # GET /tubes.json
  def index
    @tubes = Tube.all
  end

  # GET /tubes/1
  # GET /tubes/1.json
  def show
  end

  # GET /tubes/new
  def new
    @tube = Tube.new
  end

  # GET /tubes/1/edit
  def edit
  end

  # POST /tubes
  # POST /tubes.json
  def create
    @tube = Tube.new(tube_params)
    respond_to do |format|
      if @tube.save
        flash[:success] = 'Tube was successfully created.'
        format.html { redirect_to @tube }
        format.json { render :show, status: :created, location: @tube }
      else
        format.html { render :new }
        format.json { render json: @tube.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tubes/1
  # PATCH/PUT /tubes/1.json
  def update
    respond_to do |format|
      if @tube.update(tube_params)
        flash[:success] = 'Tube was successfully Update.'
        format.html { redirect_to @tube }
        format.json { render :show, status: :ok, location: @tube }
      else
        format.html { render :edit }
        format.json { render json: @tube.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tubes/1
  # DELETE /tubes/1.json
  def destroy
    @tube.destroy
    respond_to do |format|
      format.html { redirect_to tubes_url, notice: 'Tube was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tube
      @tube = Tube.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tube_params
      params.require(:tube).permit(:title, :transcript , :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tubes_helper.rb
module TubesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mltube</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>

  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">

        <strong>MLTube</strong>
      </a>
      <div class="navbar-nav ml-auto">
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
      <%= link_to 'Upload', new_tube_path ,:class=>"btn btn-outline-success my-1 ml-2"%>

    </div>

  </div>
</header>
<%= yield %>
</body>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>


  </div>
</footer>
</html>

app/views/tubes/_form.html.erb
<%= form_with(model: tube, local: true) do |form| %>
  <% if tube.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tube.errors.count, "error") %> prohibited this tube from being saved:</h2>

      <ul>
        <% tube.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :tube_title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :transcript %>
    <%= form.text_area :transcript, id: :tube_transcript, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.file_field :video %>
  </div>

  <div class="form-group">
    <%= form.submit '上傳', :class => 'btn btn-primary' %>
  </div>
  </div>
<% end %>

app/views/tubes/edit.html.erb
<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-7">Edit</h1>
    </div>
  </div>


  <%= form_with(model: @tube, local: true) do |form| %>
    <% if @tube.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tube.errors.count, "error") %> prohibited this tube from being saved:</h2>

        <ul>
          <% @tube.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, id: :tube_title, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :transcript %>
      <%= form.text_area :transcript, id: :tube_transcript, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.file_field :video %>
    </div>

    <div class="form-group">
      <%= form.submit 'Comfirm', :class => 'btn btn-outline-secondary' %>
      <%= link_to 'Cancel', tubes_path, :class => 'btn btn-outline-secondary' %>
      <%= link_to 'View', @tube, :class => 'btn btn-outline-secondary' %>

    </div>
  <% end %>


</div>

app/views/tubes/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>MLTube</title>


</head>

<body>


<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">MLTube</h1>
      <p class="lead text-muted">This is a Final Project for NCTC DataScience</p>
      <p>
        <a href="#" class="btn btn-primary my-2">GitHub</a>
        <a href="#" class="btn btn-secondary my-2">About Us</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% @tubes.each do |tube| %>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <% if tube.video_url.to_s != "" %>
                <%= video_tag tube.video_url.to_s + '#t=10', :controls => true, :class => "card-img-top", :preload => 'metadata' %>
              <% else %>
                <%= video_tag tube.video_url.to_s, :controls => true %>
              <% end %>
              <div class="card-body">
                <p class="card-text"><%= tube.title %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to "View", tube, class: 'btn btn-sm btn-outline-secondary' %>
                  </div>
                  <small class="text-muted"><%= time_ago_in_words(tube.created_at) %></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>


    </div>
  </div>

</main>


</body>
</html>

app/views/tubes/new.html.erb
<div class='container'>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-7">Upload</h1>
    </div>
  </div>

  <%= form_with(model: @tube, local: true) do |form| %>
    <% if @tube.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tube.errors.count, "error") %> prohibited this tube from being saved:</h2>

        <ul>
          <% @tube.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, id: :tube_title, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :transcript %>
      <%= form.text_area :transcript, id: :tube_transcript, :class => "form-control" , :wrap=>"hard"%>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">Upload</span>
        </div>
        <div class="custom-file">
          <%= form.file_field :video ,:class=>'custom-file-input', :id => 'inputGroupFile01'%>
          <label class="custom-file-label" for="inputGroupFile01">Choose File</label>
        </div>
      </div>

    </div>

    <div class="form-group">
      <%= form.submit '確定', :class => 'btn btn-primary' %>
      <%= link_to '取消', tubes_path, :class => 'btn btn-primary' %>
    </div>
  <% end %>

</div>

app/views/tubes/show.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <p id="notice"><%= notice %></p>

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-7"><%= @tube.title %></h1>
    </div>
  </div>

  <div class="container text-center">
    <p>
      <%= video_tag @tube.video_url.to_s, :height => '500', :controls => true %>
    </p>
  </div>
  <div class="container  px-2 py-2 ">
    <ul class="nav nav-tabs " id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">中文字幕</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Google翻譯版本</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">英文原稿</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab"><%= simple_format(@tube.transcript) %></div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
    </div>
  </div>

  <%= link_to 'Edit', edit_tube_path(@tube), :class => 'btn btn-outline-secondary' %>
  <%= link_to 'Back', tubes_path, :class => 'btn btn-outline-secondary' %>
</div>